In [1]:
import pandas as pd
import altair as alt

In [2]:
temp_data = pd.read_clipboard()

In [3]:
temp_data

      구단  득점  도움   슈팅  유효 슈팅  블락된슈팅  벗어난슈팅  Conversion Rate
0     강원  58  38  394    153     78    163           0.1472
1     광주  40  23  386    136     77    173           0.1036
2     김천  50  27  442    154     92    196           0.1131
3     대구  40  21  411    141     79    191           0.0973
4     대전  36  23  293    109     61    123           0.1229
5     서울  49  39  353    143     69    141           0.1388
6   수원FC  47  34  427    144     90    193           0.1101
7     울산  53  32  385    165     70    150           0.1377
8     인천  32  19  349    106     50    193           0.0917
9     전북  45  31  351    106     75    170           0.1282
10    제주  32  13  427    143     78    206           0.0749
11    포항  51  30  370    133     60    177           0.1378

In [4]:
temp_data['games'] =33
temp_data

      구단  득점  도움   슈팅  유효 슈팅  블락된슈팅  벗어난슈팅  Conversion Rate  games
0     강원  58  38  394    153     78    163           0.1472     33
1     광주  40  23  386    136     77    173           0.1036     33
2     김천  50  27  442    154     92    196           0.1131     33
3     대구  40  21  411    141     79    191           0.0973     33
4     대전  36  23  293    109     61    123           0.1229     33
5     서울  49  39  353    143     69    141           0.1388     33
6   수원FC  47  34  427    144     90    193           0.1101     33
7     울산  53  32  385    165     70    150           0.1377     33
8     인천  32  19  349    106     50    193           0.0917     33
9     전북  45  31  351    106     75    170           0.1282     33
10    제주  32  13  427    143     78    206           0.0749     33
11    포항  51  30  370    133     60    177           0.1378     33

In [5]:
temp_data['shots_per_game'] = temp_data['슈팅'] / temp_data['games']
temp_data

,구단,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,Conversion Rate,games,shots_per_game
0,강원,58,38,394,153,78,163,0.1472,33,11.939394
1,광주,40,23,386,136,77,173,0.1036,33,11.696970
2,김천,50,27,442,154,92,196,0.1131,33,13.393939
3,대구,40,21,411,141,79,191,0.0973,33,12.454545
4,대전,36,23,293,109,61,123,0.1229,33,8.878788
5,서울,49,39,353,143,69,141,0.1388,33,10.696970
6,수원FC,47,34,427,144,90,193,0.1101,33,12.939394
7,울산,53,32,385,165,70,150,0.1377,33,11.666667
8,인천,32,19,349,106,50,193,0.0917,33,10.575758
9,전북,45,31,351,106,75,170,0.1282,33,10.636364
10,제주,32,13,427,143,78,206,0.0749,33,12.939394
11,포항,51,30,370,133,60,177,0.1378,33,11.212121

In [6]:
(
    alt.
    Chart(temp_data).
    mark_point().
    encode(
        x = 'Conversion Rate:Q',
        y = 'shots_per_game:Q',
        color = '구단:N',
        tooltip = '구단:N'
    )
        
)

alt.Chart(...)

In [7]:
temp_pass_data = pd.read_clipboard()
temp_pass_data

      구단     시도     성공   성공%
0     강원  16010  13915  86.9
1     광주  16672  14827  88.9
2     김천  15736  13341  84.8
3     대구  13848  11556  83.4
4     대전  15030  12557  83.5
5     서울  17125  14842  86.7
6   수원FC  16446  14216  86.4
7     울산  18421  16138  87.6
8     인천  16343  13970  85.5
9     전북  15874  13593  85.6
10    제주  14875  12396  83.3
11    포항  16973  14843  87.5

In [8]:
temp_pass_data['games'] = 33
temp_pass_data['passes_attempted_per_game'] = temp_pass_data['시도'] / temp_pass_data['games']

temp_pass_data

      구단     시도     성공   성공%  games  passes_attempted_per_game
0     강원  16010  13915  86.9     33                 485.151515
1     광주  16672  14827  88.9     33                 505.212121
2     김천  15736  13341  84.8     33                 476.848485
3     대구  13848  11556  83.4     33                 419.636364
4     대전  15030  12557  83.5     33                 455.454545
5     서울  17125  14842  86.7     33                 518.939394
6   수원FC  16446  14216  86.4     33                 498.363636
7     울산  18421  16138  87.6     33                 558.212121
8     인천  16343  13970  85.5     33                 495.242424
9     전북  15874  13593  85.6     33                 481.030303
10    제주  14875  12396  83.3     33                 450.757576
11    포항  16973  14843  87.5     33                 514.333333

In [21]:
base_chart = (
    
)

point_chart = (
    alt.
    Chart(temp_pass_data).
    mark_circle(size = 200).
    encode(
        x = alt.X('성공%:Q',scale=alt.Scale(domain = [82,90])).title('PASS COMPLETION RATIO (%)'),
        y = alt.Y('passes_attempted_per_game:Q', scale = alt.Scale(domain = [400, 580])).title('PASSES ATTEMPTED PER GAME'),
        color = alt.condition(
            alt.datum.구단 == '인천',
            alt.value('blue'),
            alt.value('lightgray')
        ),
        tooltip= '구단:N'
    )
)

text_chart = (
    alt.
    Chart(temp_pass_data).
    mark_text(
        dx = 15,
        dy = 15
    ).
    encode(
        x = '성공%:Q',
        y = 'passes_attempted_per_game:Q',
        text = '구단:N',
        color = alt.condition(
            alt.datum.구단 == '인천',
            alt.value('blue'),
            alt.value('lightgray')
        )
    )
)

tot_chart = alt.layer(
    point_chart,
    text_chart
)

tot_chart.properties(
    height = 600,
    width = 800
)

xruler_chart = (

)

alt.LayerChart(...)

In [ ]:
base_chart = alt.Chart(temp_pass_data).transform_calculate(
    avg_pass = 'datum["패스 시도"]/38',
    avg_dri = 'datum["드리블 시도"]/38'
)


tot_chart = alt.layer(
    base_chart.mark_circle(size=200).encode(
        x=alt.X('avg_pass:Q').scale(domain=[250,650], bins=[300, 400, 500, 600]).title('Passes Per Match'),
        y=alt.Y('avg_dri:Q').scale(domain=[5,10.5], bins= [6,7,8,9,10]).axis(format = '0.0f').title('Dribbles Per Match'),
        color = alt.Color('split').scale(range=['#ee3224', '#001c48']).title('파이널 라운드')
    ),
    base_chart.mark_text(
        dx = 15, 
        dy = 15
    ).encode(
        x = alt.X('avg_pass:Q'),
        y = alt.Y('avg_dri:Q'),
        text= '구단',
        color = alt.Color('split').scale(range=['#ee3224', '#001c48'])
    ),
    base_chart.encode(x='med_pass:Q').mark_rule(
        stroke='gray',
        strokeDash=[5,5]
    ).transform_aggregate(
        med_pass = 'median(avg_pass)',
        med_dri = 'median(avg_dri)'
    ),
    base_chart.encode(y = 'med_dri:Q').mark_rule(
        stroke='gray',
        strokeDash=[5,5]
    ).transform_aggregate(
        med_pass = 'median(avg_pass)',
        med_dri = 'median(avg_dri)'
    ),
    base_chart.encode(
        x = 'med_pass:Q',
        y = alt.value(5),
        text = alt.value('Median Passes')
    ).mark_text(
        color='gray',
        dy = 8
    ).transform_aggregate(
        med_pass = 'median(avg_pass)',
    ),
    base_chart.encode(
        x = alt.value(50),
        y = 'med_dri:Q',
        text = alt.value('Median Dribbles')
    ).mark_text(
        dy = -10,
        color='gray'
    ).transform_aggregate(
        med_dri = 'median(avg_dri)'    
    ),
    alt.Chart().mark_rect(color = '#9D0A0F').encode(
        x = alt.value(10),
        x2 = alt.value(230),
        y = alt.value(110),
        y2 = alt.value(90),
        # color = 'red'
    ),
    alt.Chart().mark_text(color = 'white').encode(
        x = alt.value(120),
        y = alt.value(100),
        text = alt.value('Less Pass Attempt & More Dribble Attempt'),
    ),
    alt.Chart().mark_rect(color = '#9D0A0F').encode(
        x = alt.value(570),
        x2 = alt.value(790),
        y = alt.value(590),
        y2 = alt.value(570),
        # color = 'red'
    ),
    alt.Chart().mark_text(color = 'white').encode(
        x = alt.value(680),
        y = alt.value(580),
        text = alt.value('More Pass Attempt & Less Dribble Attempt'),
    )
)

tot_chart.properties(
    height = 600,
    width = 800,
    # title = alt.Title(text = 'Team Style Comparison', subtitle='2023 K League1')
).configure_axis(
    grid=False,
    ticks = False,
    domainWidth= 2,
    domainOpacity=0.4,
    labelFontSize=11,
    labelFont='Helvetica',
    labelFontStyle= 'bold',
    labelColor='gray'
).configure_view(
    stroke = None,
    fill = '#F6F6F6',
    opacity=0.3
)